services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/whoami"
      # - "traefik.http.routers.whoami.entrypoints=web"
  torch:
    build: https://github.com/jkulton/torch.git
    restart: unless-stopped
    ports:
      - "5005:5005"
    volumes:
      - /mnt/user/appdata/configs/torch.yaml:/config.yaml
